Right-click on the file in Finder and choose "Save As" or "Download Linked File" instead of opening it.

Or easier: just copy the text I'll paste below and create the file manually:

1. In your `mercor-job-monitor 2` folder, create folders: `.github/workflows/`
2. Inside `workflows`, create a new file called `monitor.yml`
3. Paste this into it:

```yaml
name: Monitor Mercor Jobs

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install playwright
        playwright install chromium
        playwright install-deps chromium
        
    - name: Run job monitor
      env:
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python monitor.py
        
    - name: Commit updated job history
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add seen_jobs.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update seen jobs [skip ci]"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
```

Save it and you're good to go.